Create Blip “looker-studio-formely-data-studio”
AlleyCorpNord/acn-radar pull request #70
Opened 2023-09-08 16:32 UTC by arnaud-fossop

Automatically generated by Decap CMS

2023-09-08 19:02 UTC, lvancraen commented on src/content/blips/looker-studio-formely-data-studio.md
> +opinion: >-
Additional comments about Looker from having used it in the past:
- It has robust RBAC allowing to use Looker within a multi-tenant architecture.
- It is relatively easy to embed looker into a webapp and slap on SSO overtop

2023-09-08 19:02 UTC, lvancraen commented on src/content/blips/looker-studio-formely-data-studio.md
> +opinion: >-
Is Looker only useable within the GCP environment? Or can it be used with AWS, for instance?

2023-09-13 15:13 UTC, arnaud-fossop commented on src/content/blips/looker-studio-formely-data-studio.md
> +opinion: >-
@lvancraen did you use Looker or Data Studio. Here we were talking about Data Studio which is a free dashboard engine from Google. I think Looker is doing much more than dashboarding.

Looker Studio can be used with different datasources (MySQL, Postgres, Amazon Redshift) so I don't think that they should be in GCP. However, the company should have a google workspace, since the users will need to be part of that workspace

2023-09-13 18:08 UTC, lvancraen commented on src/content/blips/looker-studio-formely-data-studio.md
> +opinion: >-
I'm talking about Looker. I hadn't realized that there was a difference between Looker and Looker Studio. Oops

2023-09-22 13:40 UTC, julienblin requested changes

2023-09-22 17:22 UTC, arnaud-fossop commented on src/content/blips/looker-studio-formely-data-studio.md
> +  speed up the generation of the reports.
Nope, it does not need a GCP account, only a Google account. I'll mention it

2023-09-22 21:03 UTC, jorge-vasquez-acn commented on src/content/blips/looker-studio-formely-data-studio.md
> +  Therefore the tool should be limited to simple dashboards and reports that do not require complex join/grouping.
* complex joins and aggregations.

2023-09-22 21:03 UTC, jorge-vasquez-acn commented on src/content/blips/looker-studio-formely-data-studio.md
> +link: https://lookerstudio.google.com/
Is there any good scenario to justify using this instead of tableau or PowerBI which are almost monopolies in this arena?

2023-09-25 13:53 UTC, arnaud-fossop commented on src/content/blips/looker-studio-formely-data-studio.md
> +link: https://lookerstudio.google.com/
If you have very simple use cases and do not want to pay for Tableau or PowerBI. In our case, we did not want to pay but we did not have so simple use cases 😄

2023-09-25 14:12 UTC, jorge-vasquez-acn approved these changes

2023-10-11 19:44 UTC, merged