Create Blip “gcp-artifact-registry”
AlleyCorpNord/acn-radar pull request #76
Opened 2023-09-13 18:10 UTC by arnaud-fossop

Automatically generated by Decap CMS

2023-09-22 13:32 UTC, julienblin requested changes
@arnaud-fossop - I am not sure if there is strong value documenting this one.
What does GCP artifact registry does better / or worse than competing offerings?
e.g. - would you recommend using it even if you are not in GCP?
At a high-level it feels to me like it's something you kinda need to adopt if using artifacts in a GCP deployment.

Curious to here your thoughs.

2023-09-22 15:05 UTC, lvancraen commented on src/content/blips/gcp-artifact-registry.md
> +  Docker images. GCP Artifact Registry also offer the possibility to handle
```suggestion
  Docker images. GCP Artifact Registry also offers the possibility to handle
```

2023-09-22 15:05 UTC, lvancraen commented on src/content/blips/gcp-artifact-registry.md
> +  In Docker registry, images are scan for security vulnerabilities.
```suggestion
  In Docker registry, images are scanned for security vulnerabilities.
```

2023-09-22 18:24 UTC, arnaud-fossop commented
> @arnaud-fossop - I am not sure if there is strong value documenting this one. What does GCP artifact registry does better / or worse than competing offerings? e.g. - would you recommend using it even if you are not in GCP? At a high-level it feels to me like it's something you kinda need to adopt if using artifacts in a GCP deployment.
> 
> Curious to here your thoughs.

In my previous work experience, we were using a private PyPi for Python packages, an Enterprise Docker account for Docker images, and sometimes Gitlab repository for pre-release images. When we started Synapse, we also had the choice with Github Packages. But all these options were coming with an additional cost and additional overhead to manage authentications. So that's why I am insisting on the full integration and economic aspect of using GCP Artifact registry for users in GCP (as clearly stated in my conclusion in the opinion field), and at the same time reporting about my experience with it.

If, for you, the choice of GCP Artifact Registry when you are working with GCP is natural, I cannot argue with it 😄 . So, is it valuable?

2023-09-22 20:51 UTC, jorge-vasquez-acn commented on src/content/blips/gcp-artifact-registry.md
> +  artifacts in GCP. It is notably replacing Container Registry for managing
I wonder if this tool is mature and has enough features to be considered a competitor for Nexus.  Say, I am not operating at all in GCP, is it worth it for me to install the Artifact Registry say if I am in AWS?  
That being said I find it very clever from google to merge in one place the container images and the libraries from build system tools: maven, npm, pip.  To my knowledge no other of the big cloud providers is doing this in one same place so kudos to GCP for thinking of this abstraction which is what actually Nexus does as well.

2023-09-22 20:51 UTC, jorge-vasquez-acn commented on src/content/blips/gcp-artifact-registry.md
> +  * the Python registry cannot automatically mirror the official PyPi.org (like other private PyPi servers allow to)
But I guess that from a security point of view mirroring the whole registry is not such a great idea, the security team might want to make sure that whatever library is being targeted is fully secure before opening it to the development team.

2023-09-25 14:17 UTC, arnaud-fossop commented on src/content/blips/gcp-artifact-registry.md
> +  * the Python registry cannot automatically mirror the official PyPi.org (like other private PyPi servers allow to)
I added a not about the security aspect

2023-09-25 14:25 UTC, julienblin commented
> > @arnaud-fossop - I am not sure if there is strong value documenting this one. What does GCP artifact registry does better / or worse than competing offerings? e.g. - would you recommend using it even if you are not in GCP? At a high-level it feels to me like it's something you kinda need to adopt if using artifacts in a GCP deployment.
> > Curious to here your thoughs.
> 
> In my previous work experience, we were using a private PyPi for Python packages, an Enterprise Docker account for Docker images, and sometimes Gitlab repository for pre-release images. When we started Synapse, we also had the choice with Github Packages. But all these options were coming with an additional cost and additional overhead to manage authentications. So that's why I am insisting on the full integration and economic aspect of using GCP Artifact registry for users in GCP (as clearly stated in my conclusion in the opinion field), and at the same time reporting about my experience with it.
> 
> If, for you, the choice of GCP Artifact Registry when you are working with GCP is natural, I cannot argue with it 😄 . So, is it valuable?

OK I get it now! This makes sense.
However, I don't get that level of clarity in the opinion in the blip. Could you rephrase so that this is better?
Don't get caught on generic formulation - we want clear opinions that are easy and fast to read/parse :-)

2023-09-25 14:40 UTC, arnaud-fossop commented on src/content/blips/gcp-artifact-registry.md
> +  artifacts in GCP. It is notably replacing Container Registry for managing
Nexus, Github Packages, Gitlab package registry and container registry are competitors.

2023-09-25 14:52 UTC, jorge-vasquez-acn approved these changes

2023-10-16 19:10 UTC, julienblin approved these changes
OK - thanks @arnaud-fossop for the changes!
Let's get that in!

2023-10-16 20:38 UTC, merged