Create Blip “apache-beam”
AlleyCorpNord/acn-radar pull request #77
Opened 2023-09-13 21:02 UTC by arnaud-fossop

Automatically generated by Decap CMS

2023-09-14 13:05 UTC, julienblin requested changes
I feel like this needs a bit more opinion and lessons learned - this feels like we didn't use it.

2023-09-14 13:05 UTC, julienblin commented on src/content/blips/apache-beam.md
> +ring: adopt
I don't think we are at the adopt phase if we only used it in one project. At most it should be in Trial

2023-09-14 13:05 UTC, julienblin commented on src/content/blips/apache-beam.md
> +  However it is important to note that the Apache Beam model may be not as optimized for in a given environment as the native programming model (for example: Apache Spark)
This feels very generic, and out of the website. What was _your_ experience using it like, compared to using the native environment tooling.
Why should we choose this instead of the native tooling for example.

2023-09-14 14:40 UTC, arnaud-fossop commented on src/content/blips/apache-beam.md
> +  However it is important to note that the Apache Beam model may be not as optimized for in a given environment as the native programming model (for example: Apache Spark)
I made some changes, please let me know if it is addressing that.

2023-09-22 15:01 UTC, lvancraen commented on src/content/blips/apache-beam.md
> +  However it could be good candidate to prototype faster and being able to shift from one environment to the other depending on the opportunities.
```suggestion
  However, it could be a good candidate to prototype faster and being able to shift from one environment to the other depending on the opportunities.
```

2023-09-22 15:01 UTC, lvancraen commented on src/content/blips/apache-beam.md
> +  In our current experience, using Apache Beam, it was possible to create data pipelines, test them on a single CPU with a subset of data from BigQuery (`SELECT ... from ... LIMIT n`) using the direc
Would it be worth mentioning who had this experience? As in, which team or individuals?

2023-09-22 17:29 UTC, arnaud-fossop commented on src/content/blips/apache-beam.md
> +  In our current experience, using Apache Beam, it was possible to create data pipelines, test them on a single CPU with a subset of data from BigQuery (`SELECT ... from ... LIMIT n`) using the direc
Good suggestion 🙏 . Done! please, let me know if it is ok

2023-09-22 20:32 UTC, jorge-vasquez-acn commented on src/content/blips/apache-beam.md
> +description: Apache Beam is a unified model for data processing. It provides a
I still struggle understanding the kind of product that Apache Beam is, is it an ETL product?  Maybe it can be worth comparing it with the native cloud offerings such as AWS Glue, Azure ADF, GCP DataFlow?  Is Apache Beam comparable and an alternative to these offerings?  Why would you prefer using an unmanaged service vs a managed one such as GCP DataFlow in your case where a bunch of the heavy lifting is done by the cloud provider?
Is it maybe fair to say that a more direct competitor of Apache Beam is Apache Spark?

2023-09-22 20:32 UTC, jorge-vasquez-acn commented on src/content/blips/apache-beam.md
> +
From my experience working for example with Azure ADF the reason on why it is super popular is the out-of-the-box integrations with data sources and sinks that it supports with literally the click of a button.  In the example of ADF the fact that it supports low code and full code approach via integrations such as DataBricks notebooks makes it also super interesting for potential scenarios where optimizations are required which is quite common when dealing with Big Data.

2023-09-22 20:32 UTC, jorge-vasquez-acn commented on src/content/blips/apache-beam.md
> +
In ETL tools supporting low code is a big differentiator as many companies have people that are good with queries and analytics in general but can't write code.

2023-09-22 21:55 UTC, arnaud-fossop commented on src/content/blips/apache-beam.md
> +description: Apache Beam is a unified model for data processing. It provides a
Apache Beam is a **programming model to program data transformations**. You write a program using Apache Beam API and then you can run it on GCP DataFlow or an Apache Spark cluster.

Generally, when we say Apache Spark we can be talking about the engine or the programming models. In fact, there are at least two programming models in Apache Spark: RDD and Spark SQL (when using the SQLContext and manipulating data with SQL queries). So Apache Beam could be considered a competitor programming model, because the code written with Apache Beam can also be executed on an Apache Spark cluster.

the GUI components in AWS Glue and Azure ADF are may be competitors, since they allow with no code to develop pipelines and then execute the pipeline on a managed service (generally based on Apache Spark or Hadoop MapReduce?)

2023-09-22 21:59 UTC, arnaud-fossop commented on src/content/blips/apache-beam.md
> +
I guess it always depends on the use case right? To use GCP Dataflow, you'll probably use Apache Beam under the hood, but they also provide a way to work with SQL jobs on DataFlow, or BigQuery, or whatever. The combinations today are endless. But, this will stop working as soon as you want to deal with non-standard format or data transformation. Let's say that, Apache Beam is an option in how to write your data transformations.

2023-09-25 14:31 UTC, julienblin commented
@arnaud-fossop - the opinion still feels very generic, and I agree with @jorge-vasquez-acn this is not clear what Apache Beam is.
Could you try another shot for the opinion piece? Highlight the difference with competing tools, but also bring usefule, actionable advice on when you would recommend going this route vs other approaches?

2023-09-25 15:29 UTC, arnaud-fossop commented
> @arnaud-fossop - the opinion still feels very generic, and I agree with @jorge-vasquez-acn this is not clear what Apache Beam is. Could you try another shot for the opinion piece? Highlight the difference with competing tools, but also bring usefule, actionable advice on when you would recommend going this route vs other approaches?

I gave it another try 😄 . Let me know what you think?

2023-10-11 19:37 UTC, julienblin approved these changes
I did a small update to the wording on the opinion.
Thanks @arnaud-fossop - I think this is a great explanation!

2023-10-11 19:44 UTC, merged